# -*- coding: utf-8 -*-
"""Netflix code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4ps3eDo3Sm9Ycploe1miGqduAcCXDYm
"""

# importing libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# mounting google drive
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/mymoviedb.csv',lineterminator='\n')

df.head()

# Viewing dataset info
df.info()

"""

*  Looking our dataset don't have NA!.
*  Overview, Original_Language and Poster_Url Wouldn't useful during our analysis.
*   Release _Date Column needs to casted into data time and to extract only the year value.



"""

# exploring genres column
df.Genre.head()

"""

*   Genre Column separted by commas followed by whitespace.

"""

# Checking for duplicate rows
df.duplicated().sum()

# Exploring summary statistics
df.describe()

# Data Cleaning
# casting Release _Date Column and extracing year value

df.Release_Date = pd.to_datetime(df.Release_Date)

df.Release_Date = df.Release_Date.dt.year

df.info()

# Droping column Overview, Original_Language, Poster_Url
df.drop(columns=["Overview","Original_Language","Poster_Url"],inplace=True)

"""Categorizing Vote_Average value and make 4 categories: Popular, Average, Below_avg, Not_popular"""

import pandas as pd

def categorize_col(df, col, labels):
    # Get descriptive statistics
    desc = df[col].describe()

    # Define edges using min, quartiles, and max
    edges = [desc['min'], desc['25%'], desc['50%'], desc['75%'], desc['max']]

    # Create categorized column
    df['Vote_Average'] = pd.cut(df[col], bins=edges, labels=labels, duplicates='drop')
    return df

labels = ['Not_popular', 'Below_avg', 'Average', 'Popular']
df = categorize_col(df, 'Vote_Average', labels)
df.head()

# Exploring column
df.Vote_Average.value_counts()

# Dropping NaNs
df.dropna(inplace=True)

# confirming
df.isna().sum()

# split the string into lists
df['Genre'] = df['Genre'].str.split(', ')

# explored the list
df = df.explode('Genre').reset_index(drop=True)
df.head()

# casting column into Category
df.Genre = df.Genre.astype('category')

df.Genre.dtype

df.info()

df.nunique()

"""# Data Visualization"""

# setting up seaborn configuration
sns.set_style('whitegrid')

"""# Q1: What is the most frequent genre in the dataset?"""

# showing stats. on genre column
df['Genre'].describe()

sns.catplot(
    y='Genre',                # categorical variable on Y-axis
    data=df,                  # DataFrame source
    kind='count',             # count plot (frequency of each category)
    order=df['Genre'].value_counts().index,  # order by frequency
    color='#f54242')           # bar color
plt.title('genre column distribution')
plt.show()

"""# Q2: What genres has highest votes ?"""

# visualizing vote_average column
sns.catplot(y = 'Vote_Average', data = df, kind = 'count',
order = df['Vote_Average'].value_counts().index,
color = '#42f554')
plt.title('votes destribution')
plt.show()

"""# Q3:  What movie got the highest popularity? what's it's genre ?"""

# checking max popularity in dataset
df[df['Popularity'] == df['Popularity'].max()]

"""# Q4: What movie got the lowest popularity? what's its genre?"""

# checking min popularity in dataset
df[df['Popularity']==df['Popularity'].min()]

"""# Q5: Which year has the most filmmed movies?"""

df['Release_Date'].hist()
plt.title('Release_Date distribution')
plt.ylabel('No of Movies')
plt.xlabel('year')
plt.show()